@MovieSearchBackend_HostAddress = https://localhost:7162

###

GET {{MovieSearchBackend_HostAddress}}/api/user/getAll

###

PUT {{MovieSearchBackend_HostAddress}}/api/user
Content-Type: application/json

{
  //User
}

###

POST {{MovieSearchBackend_HostAddress}}/api/user/add
Content-Type: application/json

{
  "name": "Hello",
  "email": "there@example.com",
  "biography": "friend",
  "roleId": 1
}

###

GET {{MovieSearchBackend_HostAddress}}/api/role/getAll

###

GET {{MovieSearchBackend_HostAddress}}/api/listmovie/getAll

###

GET {{MovieSearchBackend_HostAddress}}/api/list/getAll

###

PUT {{MovieSearchBackend_HostAddress}}/api/list
Content-Type: application/json


  {
    "id": 7,
    "name": "Favoritessss",
    "userId": 18,
    "listMovies": [],
    "user": null
  }

###

GET {{MovieSearchBackend_HostAddress}}/api/moviestar/getById?actorId=129700

###
